// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yurlayzxtqilrriokdps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cmxheXp4dHFpbHJyaW9rZHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzI1NjIsImV4cCI6MjA1Njc0ODU2Mn0.tuJCol4-aZS52i1Uo-o0gjpbT5L5lYl-3nMqFhCokz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);